### PR TITLE
Do not raise critical error for MessageLockLostException

### LINKED ISSUE #70: MessageLockLostException should not trigger critical errors
## Who's affected

Anyone using transport.

## Symptoms

`MessageLockLostException` thrown by the transport is raising a [critical error](https://docs.particular.net/nservicebus/hosting/critical-errors), which in turn can cause endpoints to shutdown.

## Affected supported versions

- 1.2.x
- 1.1.x

## Original issue

**Describe the bug**
When a `MessageLockLostException` occurs during message processing, the error handling pipeline will be invoked. However, the error handling pipeline will also throw the same exception because it can't recover from this exception. When `onError` throws, this error is handled as a critical error.

Some hosts will shut down on critical errors (e.g. SC) which shouldn't happen on a MessageLockLostException.

**To Reproduce**
See this transport test reproducing the issue: https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/pull/69

**Expected behavior**
Not sure whether `onError` should be called in the first place (e.g. moving message to the error queue) as I'd assume the message will be reprocessed anyway. So my first impression is that even the error handling pipeline shouldn't be invoked.

**Versions:**
latest master

### PR DESCRIPTION
**Pull request by SeanFeldman**
Fixes #70

### CODE REVIEW

File: src/Transport/Receiving/MessagePump.cs [hunk 1]
```diff
@@ -243,6 +243,10 @@ async Task ProcessMessage(Task<Message> receiveTask)
                         await receiver.SafeAbandonAsync(pushSettings.RequiredTransactionMode, lockToken).ConfigureAwait(false);
                     }
                 }
+                catch (Exception onErrorException) when (onErrorException is MessageLockLostException || onErrorException is ServiceBusTimeoutException)
+                {
+                    logger.Debug("Failed to execute recoverability.", onErrorException);
```
Comment (timbussmann) [inline src/Transport/Receiving/MessagePump.cs]: what happens with the message here given that this path won't call `SafeAbandonAsync`?

Comment (SeanFeldman) [reply src/Transport/Receiving/MessagePump.cs]: The (reference) to the message is useless to us at this point as we no longer have a valid lock or there's a timeout error, indicating we cannot communicate. The message on the broker is already consumed by another thread/consumer at this point.

Comment (timbussmann) [reply src/Transport/Receiving/MessagePump.cs]: 👍 makes sense, thanks for clarifying this. Might have been a useful comment in the code for future readers.
